# Generated by Django 4.0.5 on 2022-06-07 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('description_short', models.CharField(max_length=255)),
                ('description_long', models.TextField()),
                ('lng', models.DecimalField(decimal_places=14, max_digits=17, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('lat', models.DecimalField(decimal_places=14, max_digits=16, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
            ],
        ),
    ]
