# Generated by Django 4.0.5 on 2022-06-09 20:13

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    replaces = [('artmap_app', '0002_image_image_unique_position'), ('artmap_app', '0003_remove_image_unique_position_image_unique_position')]

    dependencies = [
        ('artmap_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_in_order', models.PositiveSmallIntegerField(default=0)),
                ('pict', models.ImageField(upload_to='')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artmap_app.place')),
            ],
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(django.db.models.expressions.F('place'), django.db.models.expressions.F('position_in_order'), name='unique_position'),
        ),
        migrations.RemoveConstraint(
            model_name='image',
            name='unique_position',
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(fields=('place', 'position_in_order'), name='unique_position'),
        ),
    ]
