# Generated by Django 4.0.5 on 2022-06-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artmap_app', '0002_image_image_unique_position_squashed_0003_remove_image_unique_position_image_unique_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='details_url',
            field=models.URLField(default=''),
        ),
    ]
