# Generated by Django 4.0.5 on 2022-06-15 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artmap_app', '0004_remove_place_details_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['position_in_order']},
        ),
        migrations.RemoveConstraint(
            model_name='image',
            name='unique_position',
        ),
    ]
