# Generated by Django 4.0.5 on 2022-06-15 19:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('artmap_app', '0005_alter_image_options_remove_image_unique_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(),
        ),
    ]
